apiVersion: apps/v1

kind: Deployment

metadata:
  name: llm-api

spec:
  replicas: 1

  selector: 
    matchLabels:
      app: llm-api

  template:
    metadata:
      labels:
        app: llm-api

    spec:
      containers:
      - name: llm-api
        image: ashishhake007/llm-api:v1
        ports:
        - containerPort: 8000